#!/bin/bash
exec 3>&1
exec >&/dev/null
echo 1>&3 "Stopping kafka"
kill -9 $(ps -ax | grep -v grep | grep -i kafka | awk '{print $1}')
echo 1>&3 "Stopping Zookeeper"
sudo service zookeeper stop
echo 1>&3 "Clearing all databases"
rm -r ~/.ethereumH/*/
rm ~/.ethereumH/indexOffset
sudo -u postgres dropdb eth
sudo -u postgres createdb eth
echo 1>&3 "Starting Zookeeper"
sudo service zookeeper start
sleep 2
echo 1>&3 "Starting kafka"
~/kafka/doit 
sleep 2
echo 1>&3 "Initializing the database"
( cd ../blockapps-data; strato-setup )
