#!/bin/bash
. setup_functions.sh

# the setup_$1.sh script must define:
# - get_dependencies(),
# - db_conf_dir (where pg_hba.conf lives)
. setup_$1.sh

get_dependencies() &&
get_mgit() &&
set_localbinpath() &&
get_ethereumH() &&
install_solc() &&
build_ethereumH() &&
setup_dbs()

if [[ $? == 0 && "$2" == "private" ]]; then
    install_auth() && setup_nginx()
fi
