#!/bin/bash
set -e

if [ $# == 0 ]
then
  base="$HOME"
else
  base=$1
  shift
fi

#useradd kafka -m

#passwd kafka
#adduser kafka sudo
#su - kafka

sudo apt-get -y update
sudo apt-get -y install default-jre zookeeperd

#telnet localhost 2181
wget "http://mirror.cc.columbia.edu/pub/software/apache/kafka/0.8.2.1/kafka_2.11-0.8.2.1.tgz" -O $base/kafka.tgz
mkdir -p $base/kafka && cd $base/kafka
tar -xvzf $base/kafka.tgz --strip 1
rm $base/kafka.tgz

sed -i 's@/tmp/kafka-logs@/var/lib/kafka@' $base/kafka/config/server.properties

echo "export KAFKA_HEAP_OPTS=\"-Xmx256M -Xms128M\"" > $base/kafka/doit
echo "nohup $base/kafka/bin/kafka-server-start.sh $base/kafka/config/server.properties > $base/kafka/kafka.log 2>&1 &" >> $base/kafka/doit
chmod 755 $base/kafka/doit
