flags: {}
packages:
- ethereum-rlp/
- ethereum-conf/
- hminer/
- ethereum-merkle-patricia-db/
- ethereum-client-haskell/
- solidity-abi/
- ethereum-data-sql/
- ethereum-encryption/
- ethereum-vm/
- ethereum-util/
- hserver-eth/
- p2p-server/
- ethereum-query/
- yesod-raml/
extra-deps: 
- Crypto-4.2.5.1
- SHA2-0.2.5
- haskoin-0.1.0.2
- leveldb-haskell-0.6.3
- AES-0.2.9
- json-rpc-0.2.1.6
- nibblestring-0.0.3
- pbkdf-1.1.1.1
- text-1.1.1.4
- directory-1.2.3.1
resolver: lts-2.15
