#!/bin/bash

nohup strato-p2p-server --runUDPServer=false -a 40.76.57.208 -p 30303 > logs/strato-p2p-server &
nohup ethereum-discover 40.76.57.208 30303 > logs/ethereum-discover &
cd strato-api
nohup strato-api > ../logs/strato-api &
cd ..
nohup ethereum-vm --miningVerification=false > logs/ethereum-vm &
nohup strato-p2p-client 2 --networkID=1001001 > logs/strato-p2p-client &
